### ISSUE TITLE
SSL Certification Invalid

### ISSUE THREAD

**Issue by msicil** [bold-commerce/bold-subscriptions-manage-subscriptions-app#4]
When I yarn start and try to load the page in my browser, I get a Privacy warning screen and a ERR: CERT INVALID error.  Looks like the code that generated the SSL certificate is outdated?

![image](https://user-images.githubusercontent.com/8879935/73561223-a1aae900-4426-11ea-8317-66311f0fa21d.png)

**Comment by rickywiens** [comment]
Hey @msicil thanks for reaching out!

https://github.com/bold-commerce/bold-subscriptions-manage-subscriptions-app#troubleshooting

Are you able to resolve that issue with these troubleshooting steps? This library doesn't provide SSL generation as part of its' setup for local dev.

**Comment by msicil** [comment]
Ricky,

Just tried those troubleshooting steps and disabling the chrome protection got me through that screen.  However when I load https://localhost:8080/app.bundle.js I get a bunch of javascript code on the screen.  I'm using npm instead of yarn, not sure if that could be causing the issue.

![image](https://user-images.githubusercontent.com/8879935/73561822-c05daf80-4427-11ea-807a-7e272689867f.png)

**Comment by rickywiens** [comment]
Yep! That means it's working!

You can follow the setup steps here to load that local bundle inside your own Shopify proxy page:

https://github.com/bold-commerce/bold-subscriptions-manage-subscriptions-app#previewing-the-local-bundle

**Comment by msicil** [comment]
Great thanks, will follow those and see if I can get this working.
